// Code generated by MockGen. DO NOT EDIT.
// Source: internal/acceptedrisks/service/service.go
//
// Generated by this command:
//
//	mockgen -package mock -destination internal/acceptedrisks/service/mock/service.go -source internal/acceptedrisks/service/service.go AcceptedRisksService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	v1 "github.com/mindersec/minder/pkg/api/protobuf/go/minder/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockAcceptedRisksService is a mock of AcceptedRisksService interface.
type MockAcceptedRisksService struct {
	ctrl     *gomock.Controller
	recorder *MockAcceptedRisksServiceMockRecorder
	isgomock struct{}
}

// MockAcceptedRisksServiceMockRecorder is the mock recorder for MockAcceptedRisksService.
type MockAcceptedRisksServiceMockRecorder struct {
	mock *MockAcceptedRisksService
}

// NewMockAcceptedRisksService creates a new mock instance.
func NewMockAcceptedRisksService(ctrl *gomock.Controller) *MockAcceptedRisksService {
	mock := &MockAcceptedRisksService{ctrl: ctrl}
	mock.recorder = &MockAcceptedRisksServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAcceptedRisksService) EXPECT() *MockAcceptedRisksServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAcceptedRisksService) Create(ctx context.Context, projectID uuid.UUID, acceptedRisk *v1.AcceptedRisk) (*v1.AcceptedRisk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, projectID, acceptedRisk)
	ret0, _ := ret[0].(*v1.AcceptedRisk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAcceptedRisksServiceMockRecorder) Create(ctx, projectID, acceptedRisk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAcceptedRisksService)(nil).Create), ctx, projectID, acceptedRisk)
}

// Delete mocks base method.
func (m *MockAcceptedRisksService) Delete(ctx context.Context, projectID, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, projectID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAcceptedRisksServiceMockRecorder) Delete(ctx, projectID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAcceptedRisksService)(nil).Delete), ctx, projectID, id)
}

// List mocks base method.
func (m *MockAcceptedRisksService) List(ctx context.Context, projectID uuid.UUID) ([]*v1.AcceptedRisk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, projectID)
	ret0, _ := ret[0].([]*v1.AcceptedRisk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockAcceptedRisksServiceMockRecorder) List(ctx, projectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAcceptedRisksService)(nil).List), ctx, projectID)
}
