// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accepted_risks.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAcceptedRisk = `-- name: CreateAcceptedRisk :one
INSERT INTO accepted_risks (
    project_id,
    entity_id,
    rule_type_id,
    expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, project_id, entity_id, rule_type_id, expires_at, created_at
`

type CreateAcceptedRiskParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	EntityID   uuid.UUID `json:"entity_id"`
	RuleTypeID uuid.UUID `json:"rule_type_id"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) CreateAcceptedRisk(ctx context.Context, arg CreateAcceptedRiskParams) (AcceptedRisk, error) {
	row := q.db.QueryRowContext(ctx, createAcceptedRisk,
		arg.ProjectID,
		arg.EntityID,
		arg.RuleTypeID,
		arg.ExpiresAt,
	)
	var i AcceptedRisk
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityID,
		&i.RuleTypeID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAcceptedRisk = `-- name: DeleteAcceptedRisk :exec
DELETE FROM accepted_risks
WHERE id = $1 AND project_id = $2
`

type DeleteAcceptedRiskParams struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteAcceptedRisk(ctx context.Context, arg DeleteAcceptedRiskParams) error {
	_, err := q.db.ExecContext(ctx, deleteAcceptedRisk, arg.ID, arg.ProjectID)
	return err
}

const deleteExpiredAcceptedRisk = `-- name: DeleteExpiredAcceptedRisk :exec
DELETE FROM accepted_risks
WHERE project_id = $1
  AND entity_id = $2
  AND rule_type_id = $3
  AND expires_at <= NOW()
`

type DeleteExpiredAcceptedRiskParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	EntityID   uuid.UUID `json:"entity_id"`
	RuleTypeID uuid.UUID `json:"rule_type_id"`
}

func (q *Queries) DeleteExpiredAcceptedRisk(ctx context.Context, arg DeleteExpiredAcceptedRiskParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAcceptedRisk, arg.ProjectID, arg.EntityID, arg.RuleTypeID)
	return err
}

const getActiveAcceptedRisk = `-- name: GetActiveAcceptedRisk :one
SELECT id, project_id, entity_id, rule_type_id, expires_at, created_at
FROM accepted_risks
WHERE project_id = $1
  AND entity_id = $2
  AND rule_type_id = $3
  AND expires_at > NOW()
`

type GetActiveAcceptedRiskParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	EntityID   uuid.UUID `json:"entity_id"`
	RuleTypeID uuid.UUID `json:"rule_type_id"`
}

func (q *Queries) GetActiveAcceptedRisk(ctx context.Context, arg GetActiveAcceptedRiskParams) (AcceptedRisk, error) {
	row := q.db.QueryRowContext(ctx, getActiveAcceptedRisk, arg.ProjectID, arg.EntityID, arg.RuleTypeID)
	var i AcceptedRisk
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EntityID,
		&i.RuleTypeID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAcceptedRisksByProjectID = `-- name: ListAcceptedRisksByProjectID :many
SELECT id, project_id, entity_id, rule_type_id, expires_at, created_at
FROM accepted_risks
WHERE project_id = $1
  AND expires_at > NOW()
ORDER BY created_at ASC
`

func (q *Queries) ListAcceptedRisksByProjectID(ctx context.Context, projectID uuid.UUID) ([]AcceptedRisk, error) {
	rows, err := q.db.QueryContext(ctx, listAcceptedRisksByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcceptedRisk{}
	for rows.Next() {
		var i AcceptedRisk
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EntityID,
			&i.RuleTypeID,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
